version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sportsbook_postgres
    environment:
      POSTGRES_DB: sportsbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sportsbook_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: sportsbook_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - sportsbook_net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: sportsbook_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - sportsbook_net

volumes:
  postgres_data:

networks:
  sportsbook_net:
    name: sportsbook_net